[package]
name = "js-source-scopes"
version = "0.3.1"
edition = "2021"

description = "Utilities for extracting and dealing with scope information in JS code"
authors = ["Sentry <hello@sentry.io>"]
license = "Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/js-source-scopes"
homepage = "https://github.com/getsentry/js-source-scopes"
repository = "https://github.com/getsentry/js-source-scopes"

[dependencies]
swc_common = "0.29.5"
swc_ecma_parser = "0.122.6"
swc_ecma_visit = { version = "0.80.5", features = ["path"] }
indexmap = "1.7.0"
sourcemap = "6.0.2"
thiserror = "1.0.32"
tracing = "0.1.36"
