[package]
name = "js-source-scopes"
version = "0.1.0"
edition = "2021"

[dependencies]
#swc_ecma_parser = "0.103.0"
thiserror = "1.0.32"
rslint_parser = "0.3.1"
sourcemap = "6.0.2"
zerocopy = "0.6.1"
leb128 = "0.2.5"
indexmap = "1.7.0"
