[package]
name = "js-source-scopes"
version = "0.3.2"
edition = "2021"

description = "Utilities for extracting and dealing with scope information in JS code"
authors = ["Sentry <hello@sentry.io>"]
license = "Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/js-source-scopes"
homepage = "https://github.com/getsentry/js-source-scopes"
repository = "https://github.com/getsentry/js-source-scopes"

[dependencies]
indexmap = "2.0.0"
sourcemap = "7.0.0"
swc_common = "0.32.1"
swc_ecma_parser = "0.140.0"
swc_ecma_visit = { version = "0.95.1", features = ["path"] }
thiserror = "1.0.32"
tracing = "0.1.36"
